### ISSUE TITLE
SyntaxError: invalid syntax in ".../sound/__init__.py" 

### ISSUE THREAD

**Issue by davidmikolas** [rhelmot/sound-machine#3]
Have I done something wrong?

   (base) david-selfs-Air:~ david$ pip install sound-machine
    Collecting sound-machine
      Downloading https://files.pythonhosted.org/packages/42/54/257166995f49b9532bdf2a544659a6201febbb4fcd85fd3999f020c339c4/sound_machine-1.0-py2.py3-none-any.whl
    Requirement already satisfied: numpy in /Users/david/anaconda3/lib/python3.7/site-packages (from sound-machine) (1.17.3)
    Collecting progressbar
      Downloading https://files.pythonhosted.org/packages/a3/a6/b8e451f6cff1c99b4747a2f7235aa904d2d49e8e1464e0b798272aa84358/progressbar-2.5.tar.gz
    Collecting sounddevice
      Downloading https://files.pythonhosted.org/packages/47/81/e83ee92b24b09cb7fef4b1bdae88e4b453b54fefa05e57e89dda1ef1f0ad/sounddevice-0.4.1-py3.cp32.cp33.cp34.cp35.cp36.cp37.cp38.cp39.pp32.pp33.pp34.pp35.pp36.pp37-none-macosx_10_6_x86_64.whl (78kB)
         |████████████████████████████████| 81kB 1.2MB/s
    Requirement already satisfied: CFFI>=1.0 in /Users/david/anaconda3/lib/python3.7/site-packages (from sounddevice->sound-machine) (1.13.2)
    Requirement already satisfied: pycparser in /Users/david/anaconda3/lib/python3.7/site-packages (from CFFI>=1.0->sounddevice->sound-machine) (2.19)
    Building wheels for collected packages: progressbar
      Building wheel for progressbar (setup.py) ... done
      Created wheel for progressbar: filename=progressbar-2.5-cp37-none-any.whl size=12073 sha256=e6b0b5a7c7833d7ef7fce145d31d4a533f30db8ccedfa08e495ac4c920bc470d
      Stored in directory: /Users/david/Library/Caches/pip/wheels/c0/e9/6b/ea01090205e285175842339aa3b491adeb4015206cda272ff0
    Successfully built progressbar
    Installing collected packages: progressbar, sounddevice, sound-machine
    Successfully installed progressbar-2.5 sound-machine-1.0 sounddevice-0.4.1
   
Then:

    (base) david-selfs-Air:~ david$ python
    Python 3.7.3 (default, Mar 27 2019, 16:54:48)
    [Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import sound
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/david/anaconda3/lib/python3.7/site-packages/sound/__init__.py", line 7
        from . import sample, envelope, filter, instrument, notes, async
                                                                       ^
    SyntaxError: invalid syntax

**Comment by rhelmot** [comment]
unfortunately this project is incompatible with python 3.7, which adds the `async` keyword which I was using as an identifier :(

**Comment by davidmikolas** [comment]
Oh I see. Okay I will look into making an environment with an earlier version. I know it's not difficult but I have to go look it up.

Thanks for the speedy reply! Feel free to close the issue if you're planning on staying at 3.6
